version: '3'


services:
  mysql:
    container_name: photorize-mysql
    image: mysql:8.0.33
    restart: always
    ports:
      - "3307:3306"
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_DATABASE: photorizedb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - photorize-backend

  redis:
    container_name: photorize-redis
    image: redis:7.0.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - photorize-backend

  elasticsearch:
    container_name: photorize-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - photorize-backend

networks:
  photorize-backend:
    driver: bridge

volumes:
  mysql_data:
  elasticsearch_data:
